#author: Ondrej Lukasek (xlukas15)

ITY_PROJEKT=proj5

all:
	pdflatex $(ITY_PROJEKT).tex
	pdflatex $(ITY_PROJEKT).tex

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.nav
	rm -f *.out
	rm -f *.snm
	rm -f *.toc
